name: 'reporter'

on:
  pull_request:
    branches:
      - main

jobs:
  troubleshooting:
    permissions:
      issues: 'write'

    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/github-script@v6'
        with:
          script: |-
                  const date = new Date();
                  date.setDate(date.getDate() - 1);
                  const commits = await github.paginate(github.rest.repos.listCommits, {
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    since:  date.toISOString(),
                  });
                  const createIssue = async function(title,txt) {
                    github.rest.issues.create({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      title: title,
                      body: txt,
                      labels: "test",
                    })
                  }


                  var foundCheck =false
                  let periodicCheck = {};
                  for (const commit of commits) {
                  const checks = await github.rest.checks.listForRef({
                    ref: commit.sha,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                  });
                  for (const check of checks.data.check_runs) {
                      if (check.name.includes('periodic-int-trigger')) {
                            foundCheck = true
                            periodicCheck = check
                            break
                        }
                  } 
                  if (foundCheck) {
                      console.log("found check");
                      console.log(periodicCheck.url)
                      createIssue("passed", periodicCheck.url)
                  } else {
                      console.log("didnt find check");
                  }
                  }
